table olist_customers_dataset
	lineageTag: 7ae7f22a-efe1-43f4-b09f-2f9c79ce1ab7

	measure '% Atraso' = ```
			
			DIVIDE(
			    COUNTROWS(FILTER('olist_orders_dataset', 
			        'olist_orders_dataset'[order_delivered_customer_date] > 
			        'olist_orders_dataset'[order_estimated_delivery_date])),
			    COUNTROWS('olist_orders_dataset')
			) * 100
			```
		lineageTag: 03d16aa1-6eda-4284-afd0-70281541bb04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media de Avaliacao para pedidos atrasados' = ```
			
			CALCULATE(
			    AVERAGE('olist_order_reviews_dataset'[review_score]),
			    'olist_orders_dataset'[order_delivered_customer_date] > 
			    'olist_orders_dataset'[order_estimated_delivery_date]
			)
			```
		lineageTag: 90bdd994-7d3e-408f-98a1-e05c52b91370

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media Avaliacao para pedidos no prazo' = ```
			
			CALCULATE(
			    AVERAGE('olist_order_reviews_dataset'[review_score]),
			    'olist_orders_dataset'[order_delivered_customer_date] <= 
			    'olist_orders_dataset'[order_estimated_delivery_date]
			)
			```
		lineageTag: fe507980-77b3-4b14-b7f2-c5d15c92f6ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_id
		dataType: string
		lineageTag: 80cde1d5-469f-4e89-b639-2e217f4031e4
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: 86a882b2-121d-4682-8e8e-f18c28642139
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 898ceaa0-a2a8-48d4-a8c2-edef42d6423a
		summarizeBy: sum
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 3810eead-bda5-4c6e-949a-c901d25384b8
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 4ac884e0-1148-4bdc-9a8d-15487fbf7e0a
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	partition olist_customers_dataset = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\alan_\OneDrive\Área de Trabalho\olist_analise\dados\olist_customers_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Usar a Primeira Linha como Cabeçalho" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Alterar Tipo" = Table.TransformColumnTypes(#"Usar a Primeira Linha como Cabeçalho",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}})
				in
				    #"Alterar Tipo"

	annotation PBI_ResultType = Table

